In [ ]:
# Install the PyDrive wrapper & import libraries.
# This only needs to be done once per notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1Sv4ib5i7CKWhAHZkKg-uitIkS3xwxtXM'
downloaded = drive.CreateFile({'id': file_id})



In [ ]:
from google.colab import drive


Mounted at /content/drive


In [ ]:
# Initializing and Setting up Data (Item Item Approach)
import pandas as pd
import numpy as np
from numpy.linalg import norm

df = pd.read_excel('/content/drive/My Drive/Homework 4 Information Insights/HW4_Data_2022_Updated_v2.xlsx','Final Transposed and UpdateData')
#df = df.fillna(0)
df = df.drop(df.columns[290], axis = 1)
df = df.drop(df.columns[294], axis = 1)
df = df.drop(df.columns[312], axis = 1)
df = df.drop(df.columns[320], axis = 1)

df3 = df.transpose()

new_header = df3.iloc[0] #grab the first row for the header
df3 = df3[1:] #take the data less the header row
df3.columns = new_header.str.replace(' ', '')

print(df3.std())

User_Info = ['Camile',2,2,4,3,3],['Shachi',4,5,5,4,3],['Amy',4,3,4,1,4]
User_DF = pd.DataFrame(User_Info,columns = ['User','Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3'],index = ['Camile','Shachi','Amy'])
print(User_DF)


print(User_DF)


##df3.columns = list(df[0])




FileNotFoundError: ignored

In [ ]:
## Normal Value Approach

Movie_Val = ['Inception','Avatar','TheWolfofWallStreet']
Ans_Vec = []

Var1 = 0
for itr in Movie_Val:
  print("Var :"+str(Var1))
  #Q4_Dataset_Inception = df3.loc[df3[itr] != 0]
  Q4_Dataset_Inception = df3.loc[(df3[itr]).notna()]

  #print(Q4_Dataset_Inception[itr])
  #print(Q4_Dataset_Inception_2)

  DF4 = Q4_Dataset_Inception.loc[:,['Inception','Avatar','TheWolfofWallStreet','Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]

  Cos_Vector = []

  for i in range(3,8):
    print(i)
    A = DF4.iloc[:,Var1].fillna(0)
    B = DF4.iloc[:,i].fillna(0)
    cosine = np.dot(A,B)/(norm(A)*norm(B))
    Cos_Vector = np.append(Cos_Vector,cosine)
    Abs_Cos_Vector = np.absolute(Cos_Vector)

  print(Cos_Vector)

##f3
  Var1 = Var1 + 1
  finans = (User_DF.loc[:, User_DF.columns != 'User']*Cos_Vector).sum(axis = 1)/Abs_Cos_Vector.sum()
  Ans_Vec = np.append(Ans_Vec,finans)
  print(Ans_Vec)
##

Var :0
3
4
5
6
7
[0.3055522  0.56660292 0.70669679 0.69428691 0.76001289]
[2.94545003 4.16922557 3.12649814]
Var :1
3
4
5
6
7
[0.29557103 0.55372715 0.67071281 0.67907028 0.76060964]
[2.94545003 4.16922557 3.12649814 2.9396608  4.1567158  3.1245917 ]
Var :2
3
4
5
6
7
[0.3268595  0.57633759 0.71841782 0.70411542 0.76097313]
[2.94545003 4.16922557 3.12649814 2.9396608  4.1567158  3.1245917
 2.94013702 4.17292956 3.1289465 ]


In [ ]:
# Mean Scored Approach

Movie_Val = ['Inception','Avatar','TheWolfofWallStreet']
#Movie_Val = ['Inception']
Ans_Vec = []
User_DF2 = User_DF.loc[:, User_DF.columns != 'User'] - User_DF.loc[:, User_DF.columns != 'User'].mean()


Var1 = 0
for itr in Movie_Val:
  print("Var :"+str(Var1))
  Q4_Dataset_Inception = df3.loc[df3[itr] != 0]


  DF4_Intermed = Q4_Dataset_Inception.loc[:,['Inception','Avatar','TheWolfofWallStreet','Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  DF4 = DF4_Intermed - DF4_Intermed.mean()
  Cos_Vector = []

  Part1_DF = Q4_Dataset_Inception.loc[:,['Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  Part2_DF = User_DF.loc[:,['Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  Agg_DF = []
  Agg_DF = pd.concat([Part1_DF,Part2_DF], ignore_index=True)
  #print(Agg_DF)

  Agg_DF_2 = Agg_DF - Agg_DF.mean()

  #print(Agg_DF_2.tail(3))


  for i in range(3,8):
    print(i)
    A = DF4.iloc[:,Var1].fillna(0)
    B = DF4.iloc[:,i].fillna(0)
    cosine = np.dot(A,B)/(norm(A)*norm(B))
    Cos_Vector = np.append(Cos_Vector,cosine)
    Abs_Cos_Vector = np.absolute(Cos_Vector)

  print(Cos_Vector)

  print(Q4_Dataset_Inception[itr].mean())
##f3

  finans = Q4_Dataset_Inception[itr].mean() + (Agg_DF_2.tail(3)*Cos_Vector).sum(axis = 1)/(Abs_Cos_Vector).sum()
  #Ans_Vec = pd.concat([Ans_Vec,finans], ignore_index=True)
  #Ans_Vec[Var1] = finans
  Ans_Vec = np.append(Ans_Vec,finans)
  Var1 = Var1 + 1
  print(Ans_Vec)

Var :0
3
4
5
6
7
[0.22707292 0.09749994 0.24654745 0.2458     0.25873518]
4.485436893203883
[3.55850997 4.71035936 3.85486969]
Var :1
3
4
5
6
7
[0.12744425 0.12650063 0.15651454 0.25276927 0.22297058]
4.015290519877676
[3.55850997 4.71035936 3.85486969 3.00471923 4.18241621 3.11623044]
Var :2
3
4
5
6
7
[0.12184595 0.12242865 0.18359513 0.16719487 0.08030095]
4.118055555555555
[3.55850997 4.71035936 3.85486969 3.00471923 4.18241621 3.11623044
 3.16453654 4.58860659 3.33041968]


In [ ]:
## Z Scored Approac Item Item Method

Movie_Val = ['Inception','Avatar','TheWolfofWallStreet']
#Movie_Val = ['Inception']
Ans_Vec = []
User_DF2 = User_DF.loc[:, User_DF.columns != 'User'] - User_DF.loc[:, User_DF.columns != 'User'].mean()


Var1 = 0
for itr in Movie_Val:
  print("Var :"+str(Var1))
  Q4_Dataset_Inception = df3.loc[df3[itr] != 0]


  DF4_Intermed = Q4_Dataset_Inception.loc[:,['Inception','Avatar','TheWolfofWallStreet','Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  DF4 = (DF4_Intermed - DF4_Intermed.mean())/DF4_Intermed.std()
  Cos_Vector = []

  Part1_DF = Q4_Dataset_Inception.loc[:,['Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  Part2_DF = User_DF.loc[:,['Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  Agg_DF = []
  Agg_DF = pd.concat([Part1_DF,Part2_DF], ignore_index=True)
  #print(Agg_DF)

  Agg_DF_2 = (Agg_DF - Agg_DF.mean())/Agg_DF.std()

  #print(Agg_DF_2.tail(3))


  for i in range(3,8):
    print(i)
    A = DF4.iloc[:,Var1].fillna(0)
    B = DF4.iloc[:,i].fillna(0)
    cosine = np.dot(A,B)/(norm(A)*norm(B))
    Cos_Vector = np.append(Cos_Vector,cosine)
    Abs_Cos_Vector = np.absolute(Cos_Vector)

  print(Cos_Vector)

  print(Q4_Dataset_Inception[itr].mean())
  print(Q4_Dataset_Inception[itr].std())
##f3

  finans = Q4_Dataset_Inception[itr].mean() + (Q4_Dataset_Inception[itr].std())*(Agg_DF_2.tail(3)*Cos_Vector).sum(axis = 1)/(Abs_Cos_Vector).sum()
  #Ans_Vec = pd.concat([Ans_Vec,finans], ignore_index=True)
  #Ans_Vec[Var1] = finans
  Ans_Vec = np.append(Ans_Vec,finans)
  Var1 = Var1 + 1
  print(Ans_Vec)

Var :0
3
4
5
6
7
[0.22707292 0.09749994 0.24654745 0.2458     0.25873518]
4.485436893203883
0.8512490174287622
[3.67117815 4.62434225 3.92593182]
Var :1
3
4
5
6
7
[0.12744425 0.12650063 0.15651454 0.25276927 0.22297058]
4.015290519877676
1.0226327555689834
[3.67117815 4.62434225 3.92593182 2.95635126 4.13054384 3.0680292 ]
Var :2
3
4
5
6
7
[0.12184595 0.12242865 0.18359513 0.16719487 0.08030095]
4.118055555555555
0.9444245175643704
[3.67117815 4.62434225 3.92593182 2.95635126 4.13054384 3.0680292
 3.20049675 4.50064797 3.3477584 ]


In [ ]:

# Normal Value Approach (User User Approach)

Movie_Val = ['Inception','Avatar','TheWolfofWallStreet']
Name_Arr = ['Camile','Shachi','Amy']
Ans_Vec = []

#new_header = Part2_DF.iloc[0] #grab the first row for the header
#Part2_DF = Part2_DF[1:] #take the data less the header row
#Part2_DF.columns = new_header.str.replace(' ', '')

Var1 = 0

for itr in Movie_Val:
  print("Var :"+str(Var1))
  Var1 = Var1 + 1
  #Q4_Dataset_Inception = df3.loc[df3[itr] != 0]
  Q4_Dataset_Inception = df3.loc[(df3[itr]).notna()]

  #print(Q4_Dataset_Inception)
  #print(Q4_Dataset_Inception_2)

  #DF4 = Q4_Dataset_Inception.loc[:,['Inception','Avatar','TheWolfofWallStreet','Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  #Len_Itr = len(DF4)
  #print("Length of the dataframe is"+str(len(DF4)))

  Agg_DF_1 = []

  Part1_DF = Q4_Dataset_Inception.loc[:,[itr,'Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  Part2_DF = User_DF.loc[:,['Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]

  Agg_DF_1 = pd.concat([Part1_DF,Part2_DF])

  Agg_DF_Transpose = Agg_DF_1.transpose()
  #print(Agg_DF_Transpose)
  #print("hello")
  #print(Agg_DF_Transpose.loc[itr,:])
  #print(Agg_DF_Transpose['0'])
  #Agg_DF_2 = (Agg_DF - Agg_DF.mean())/Agg_DF.std()

  Cos_Vector = []

  for name in Name_Arr:
    Cos_Vector = []
    A = Agg_DF_Transpose.loc[:,name].fillna(0)
    Agg_DF_T2 = Agg_DF_Transpose.loc[:, Agg_DF_Transpose.columns != name]
    print(len(Agg_DF_T2.columns))
    for i in range(0,len(Agg_DF_T2.columns)):
      #print(i)
      B = Agg_DF_T2.iloc[:,i].fillna(0)
      cosine = np.dot(A,B)/(norm(A)*norm(B))
      Cos_Vector = np.append(Cos_Vector,cosine)

    Abs_Cos_Vector = np.absolute(Cos_Vector)
    print(len(Cos_Vector))

    ##f3
    finans = (Agg_DF_T2.loc[itr,:]*Cos_Vector).sum()/Abs_Cos_Vector.sum()
    Ans_Vec = np.append(Ans_Vec,finans)

    print("Final Answer")
    print(Ans_Vec)
##

Var :0
311
311
Final Answer
[4.41619827]
311
311
Final Answer
[4.41619827 4.4181889 ]
311
311
Final Answer
[4.41619827 4.4181889  4.40181888]
Var :1
329
329
Final Answer
[4.41619827 4.4181889  4.40181888 3.90743525]
329
329
Final Answer
[4.41619827 4.4181889  4.40181888 3.90743525 3.90627899]
329
329
Final Answer
[4.41619827 4.4181889  4.40181888 3.90743525 3.90627899 3.90625872]
Var :2
290
290
Final Answer
[4.41619827 4.4181889  4.40181888 3.90743525 3.90627899 3.90625872
 4.05863596]
290
290
Final Answer
[4.41619827 4.4181889  4.40181888 3.90743525 3.90627899 3.90625872
 4.05863596 4.06538892]
290
290
Final Answer
[4.41619827 4.4181889  4.40181888 3.90743525 3.90627899 3.90625872
 4.05863596 4.06538892 4.05844951]


In [ ]:
# Mean Value Approach (User User Approach)

Movie_Val = ['Inception','Avatar','TheWolfofWallStreet']
Name_Arr = ['Camile','Shachi','Amy']
Ans_Vec = []

#new_header = Part2_DF.iloc[0] #grab the first row for the header
#Part2_DF = Part2_DF[1:] #take the data less the header row
#Part2_DF.columns = new_header.str.replace(' ', '')

Var1 = 0

for itr in Movie_Val:
  print("Var :"+str(Var1))
  Var1 = Var1 + 1
  #Q4_Dataset_Inception = df3.loc[df3[itr] != 0]
  Q4_Dataset_Inception = df3.loc[(df3[itr]).notna()]

  #print(Q4_Dataset_Inception)
  #print(Q4_Dataset_Inception_2)

  #DF4 = Q4_Dataset_Inception.loc[:,['Inception','Avatar','TheWolfofWallStreet','Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  #Len_Itr = len(DF4)
  #print("Length of the dataframe is"+str(len(DF4)))

  Agg_DF_1 = []

  Part1_DF = Q4_Dataset_Inception.loc[:,[itr,'Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  Part2_DF = User_DF.loc[:,['Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]

  Agg_DF_1 = pd.concat([Part1_DF,Part2_DF])

  Agg_DF_Transpose = Agg_DF_1.transpose()

  Agg_DF_Transpose_MeanDiff = Agg_DF_Transpose - Agg_DF_Transpose.mean()

  #print(Agg_DF_Transpose)
  #print("hello")
  #print(Agg_DF_Transpose.loc[itr,:])
  #print(Agg_DF_Transpose['0'])
  #Agg_DF_2 = (Agg_DF - Agg_DF.mean())/Agg_DF.std()

  Cos_Vector = []

  for name in Name_Arr:
    Cos_Vector = []
    A = Agg_DF_Transpose_MeanDiff.loc[:,name].fillna(0)
    Agg_DF_T2 = Agg_DF_Transpose_MeanDiff.loc[:, Agg_DF_Transpose_MeanDiff.columns != name]
    print(len(Agg_DF_T2.columns))
    for i in range(0,len(Agg_DF_T2.columns)):
      #print(i)
      B = Agg_DF_T2.iloc[:,i].fillna(0)
      cosine = np.dot(A,B)/(norm(A)*norm(B))
      cosine = np.nan_to_num(cosine)
      #print(norm(B))
      Cos_Vector = np.append(Cos_Vector,cosine)

    Abs_Cos_Vector = np.absolute(Cos_Vector)
    print(len(Cos_Vector))
    #print(Cos_Vector)

    ##f3
    finans = Agg_DF_Transpose.loc[:,name].mean() + (Agg_DF_T2.loc[itr,:]*Cos_Vector).sum()/Abs_Cos_Vector.sum()
    print("Mean Value")
    print(Agg_DF_Transpose.loc[:,name].mean())
    Ans_Vec = np.append(Ans_Vec,finans)

    print("Final Answer")
    print(Ans_Vec)
##

Var :0
311
311
Mean Value
2.8
Final Answer
[2.47177767]
311


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: RuntimeWarning: invalid value encountered in double_scalars


311
Mean Value
4.2
Final Answer
[2.47177767 4.16422121]
311
311
Mean Value
3.2
Final Answer
[2.47177767 4.16422121 3.08959536]
Var :1
329
329
Mean Value
2.8
Final Answer
[2.47177767 4.16422121 3.08959536 2.51642903]
329
329
Mean Value
4.2
Final Answer
[2.47177767 4.16422121 3.08959536 2.51642903 4.21495769]
329
329
Mean Value
3.2
Final Answer
[2.47177767 4.16422121 3.08959536 2.51642903 4.21495769 3.1311619 ]
Var :2
290
290
Mean Value
2.8
Final Answer
[2.47177767 4.16422121 3.08959536 2.51642903 4.21495769 3.1311619
 2.50846112]
290
290
Mean Value
4.2
Final Answer
[2.47177767 4.16422121 3.08959536 2.51642903 4.21495769 3.1311619
 2.50846112 4.25351577]
290
290
Mean Value
3.2
Final Answer
[2.47177767 4.16422121 3.08959536 2.51642903 4.21495769 3.1311619
 2.50846112 4.25351577 3.10393583]


In [ ]:
# Z Score Approach (User User Approach)

Movie_Val = ['Inception','Avatar','TheWolfofWallStreet']
Name_Arr = ['Camile','Shachi','Amy']
Ans_Vec = []

#new_header = Part2_DF.iloc[0] #grab the first row for the header
#Part2_DF = Part2_DF[1:] #take the data less the header row
#Part2_DF.columns = new_header.str.replace(' ', '')

Var1 = 0

for itr in Movie_Val:
  print("Var :"+str(Var1))
  Var1 = Var1 + 1
  #Q4_Dataset_Inception = df3.loc[df3[itr] != 0]
  Q4_Dataset_Inception = df3.loc[(df3[itr]).notna()]

  #print(Q4_Dataset_Inception)
  #print(Q4_Dataset_Inception_2)

  #DF4 = Q4_Dataset_Inception.loc[:,['Inception','Avatar','TheWolfofWallStreet','Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  #Len_Itr = len(DF4)
  #print("Length of the dataframe is"+str(len(DF4)))

  Agg_DF_1 = []

  Part1_DF = Q4_Dataset_Inception.loc[:,[itr,'Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]
  Part2_DF = User_DF.loc[:,['Precious','12YearsaSlave','MadMax:FuryRoad','BlackSwan','ToyStory3']]

  Agg_DF_1 = pd.concat([Part1_DF,Part2_DF])

  Agg_DF_Transpose = Agg_DF_1.transpose()

  Agg_DF_Transpose_ZVal = ((Agg_DF_Transpose - Agg_DF_Transpose.mean())/((Agg_DF_Transpose.std()).replace(0,1)))

  #print(Agg_DF_Transpose)
  #print("hello")
  #print(Agg_DF_Transpose.loc[itr,:])
  #print(Agg_DF_Transpose['0'])
  #Agg_DF_2 = (Agg_DF - Agg_DF.mean())/Agg_DF.std()

  Cos_Vector = []

  for name in Name_Arr:
    Cos_Vector = []
    A = Agg_DF_Transpose_ZVal.loc[:,name].fillna(0)
    Agg_DF_T2 = Agg_DF_Transpose_ZVal.loc[:, Agg_DF_Transpose_ZVal.columns != name]
    print(len(Agg_DF_T2.columns))
    for i in range(0,len(Agg_DF_T2.columns)):
      #print(i)
      B = Agg_DF_T2.iloc[:,i].fillna(0)
      cosine = np.dot(A,B)/(norm(A)*norm(B))
      cosine = np.nan_to_num(cosine)
      #print(norm(B))
      Cos_Vector = np.append(Cos_Vector,cosine)

    Abs_Cos_Vector = np.absolute(Cos_Vector)
    print(len(Cos_Vector))
    #print(Cos_Vector)

    ##f3
    finans = Agg_DF_Transpose.loc[:,name].mean() + ((Agg_DF_T2.loc[itr,:]*Cos_Vector).sum()/Abs_Cos_Vector.sum())*Agg_DF_Transpose.loc[:,name].std()
    print("Mean Value")
    print(Agg_DF_Transpose.loc[:,name].mean())
    Ans_Vec = np.append(Ans_Vec,finans)

    print("Final Answer")
    print(Ans_Vec)
##

Var :0
311


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: RuntimeWarning: invalid value encountered in double_scalars


311
Mean Value
2.8
Final Answer
[2.51224745]
311
311
Mean Value
4.2
Final Answer
[2.51224745 4.19146794]
311
311
Mean Value
3.2
Final Answer
[2.51224745 4.19146794 3.11116541]
Var :1
329
329
Mean Value
2.8
Final Answer
[2.51224745 4.19146794 3.11116541 2.54796695]
329
329
Mean Value
4.2
Final Answer
[2.51224745 4.19146794 3.11116541 2.54796695 4.24301861]
329
329
Mean Value
3.2
Final Answer
[2.51224745 4.19146794 3.11116541 2.54796695 4.24301861 3.10480301]
Var :2
290
290
Mean Value
2.8
Final Answer
[2.51224745 4.19146794 3.11116541 2.54796695 4.24301861 3.10480301
 2.56179979]
290
290
Mean Value
4.2
Final Answer
[2.51224745 4.19146794 3.11116541 2.54796695 4.24301861 3.10480301
 2.56179979 4.24388155]
290
290
Mean Value
3.2
Final Answer
[2.51224745 4.19146794 3.11116541 2.54796695 4.24301861 3.10480301
 2.56179979 4.24388155 3.10158954]
